name: daytoday_ledgerbook
description: "A new Flutter project."

publish_to: 'none'

version: 0.0.1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^3.8.0
  firebase_crashlytics: ^4.1.5
  permission_handler: ^11.3.1
  flutter_local_notifications: ^18.0.1
  open_file: ^3.5.10
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  flutter_svg: ^2.0.15
  iconsax: ^0.0.8
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2
  flutter_exif_rotation: ^0.5.2
  flutter_image_compress: ^2.3.0
  firebase_storage: ^12.3.6
  flutter_colorpicker: ^1.1.0
  flutter_native_splash: ^2.4.1
  uuid: ^4.5.1
  cloud_firestore: ^5.5.0
  intl: ^0.19.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
          style: normal
