// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

// Package imports:
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdrZXy1Fi4zxxUgo_sYqj2b8gAEFski2w',
    appId: '1:172051736995:android:20df20b806b28b799c1216',
    messagingSenderId: '172051736995',
    projectId: 'app-tester-4aa51',
    storageBucket: 'app-tester-4aa51.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0NF1X0hDmOj0blIJWaCuIUPQZ_-bqTyU',
    appId: '1:172051736995:ios:82a3567ae90f76fb9c1216',
    messagingSenderId: '172051736995',
    projectId: 'app-tester-4aa51',
    storageBucket: 'app-tester-4aa51.appspot.com',
    iosBundleId: 'com.srisoftwarez.daytodayLedgerbook',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxT95LeOjkNQ3ClXGI1oydstH7vBVakd8',
    appId: '1:172051736995:web:aa1c67364bbe21aa9c1216',
    messagingSenderId: '172051736995',
    projectId: 'app-tester-4aa51',
    authDomain: 'app-tester-4aa51.firebaseapp.com',
    storageBucket: 'app-tester-4aa51.appspot.com',
    measurementId: 'G-DWGGPZ347Q',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhyBs9KgiNlKegeXIFEPtio0dj_kgC3r8',
    appId: '1:172051736995:web:f94aa9ed423841cf9c1216',
    messagingSenderId: '172051736995',
    projectId: 'app-tester-4aa51',
    authDomain: 'app-tester-4aa51.firebaseapp.com',
    storageBucket: 'app-tester-4aa51.appspot.com',
    measurementId: 'G-48HRDN1HER',
  );

}
